---
- name: Add a backend node to HAProxy
  hosts: all
  become: true
  gather_facts: false
  vars:
    backend_name: app
    backend_servers:
      - name: server1
        ip: 10.10.10.4
        port: 80

  tasks:
    - name: Render HAProxy configuration file
      template:
        src: template/haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
      notify:
        - Restart HAProxy

  handlers:
    - name: Restart HAProxy
      service:
        name: haproxy
        state: restarted

